env:
  browser: true
extends:
  - plugin:svelte/recommended
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
overrides:
  - files: ['*.svelte']
    parser: svelte-eslint-parser
    parserOptions:
      parser: '@typescript-eslint/parser'
rules:
  indent: [error, 2, SwitchCase: 1]
  '@typescript-eslint/quotes': [error, backtick, avoidEscape: true]
  semi: [error, never]
  linebreak-style: [error, unix]
  no-console: [error, allow: [warn, error]]
  no-var: error
  '@typescript-eslint/no-inferrable-types': off
  '@typescript-eslint/no-unused-vars': [error, { argsIgnorePattern: ^_ }]
  svelte/no-at-html-tags: off
  no-inner-declarations: off
ignorePatterns: [build/]
