import yaml from '@rollup/plugin-yaml'
import { sveltekit } from '@sveltejs/kit/vite'
import { defineConfig } from 'vite-plus'

export default defineConfig({
  fmt: {
    printWidth: 90,
    semi: false,
    singleQuote: true,
  },
  lint: {
    categories: {
      correctness: `error`,
      suspicious: `error`,
      pedantic: `error`,
      perf: `error`,
      restriction: `error`,
      style: `error`,
    },
    ignorePatterns: [`build/**`, `.svelte-kit/**`, `dist/**`, `src/app.d.ts`],
    options: {
      typeAware: true,
      typeCheck: true,
    },
    plugins: [`oxc`, `typescript`, `unicorn`, `import`, `vitest`],
    rules: {
      // Extra rules not in enabled categories
      'no-console': [`error`, { allow: [`warn`, `error`] }],
      '@typescript-eslint/no-unused-vars': [
        `error`,
        { argsIgnorePattern: `^_`, varsIgnorePattern: `^_` },
      ],
      eqeqeq: `error`,
      'no-template-curly-in-string': `error`,
      'no-constructor-return': `error`,
      'default-param-last': `error`,
      'guard-for-in': `error`,
      'eslint-plugin-unicorn/prefer-array-find': `error`,
      'eslint-plugin-unicorn/no-typeof-undefined': `error`,
      'eslint-plugin-unicorn/prefer-optional-catch-binding': `error`,
      'eslint-plugin-unicorn/no-length-as-slice-end': `error`,
      'eslint-plugin-unicorn/prefer-node-protocol': `error`,
      'eslint-plugin-unicorn/throw-new-error': `error`,
      'eslint-plugin-unicorn/prefer-type-error': `error`,
      'eslint-plugin-unicorn/prefer-date-now': `error`,
      'eslint-plugin-unicorn/require-number-to-fixed-digits-argument': `error`,
      'eslint-plugin-unicorn/no-useless-promise-resolve-reject': `error`,
      'eslint-plugin-unicorn/custom-error-definition': `error`,
      'eslint-plugin-import/no-duplicates': `error`,
      '@typescript-eslint/no-non-null-assertion': `error`,
      '@typescript-eslint/prefer-string-starts-ends-with': `error`,
      '@typescript-eslint/prefer-readonly': `error`,
      '@typescript-eslint/prefer-regexp-exec': `error`,
      '@typescript-eslint/prefer-find': `error`,
      '@typescript-eslint/no-redundant-type-constituents': `warn`,
      'no-useless-computed-key': `error`,
      'eslint-plugin-vitest/prefer-strict-boolean-matchers': `error`,
      'eslint-plugin-vitest/prefer-called-exactly-once-with': `error`,
      'eslint-plugin-vitest/require-awaited-expect-poll': `error`,
      'eslint-plugin-vitest/valid-expect': [`error`, { maxArgs: 2 }],
      // Incompatible with SvelteKit conventions
      'eslint-plugin-vitest/require-hook': `off`,
      'eslint-plugin-import/no-named-export': `off`,
      'eslint-plugin-import/group-exports': `off`,
      'eslint-plugin-import/exports-last': `off`,
      'eslint-plugin-import/prefer-default-export': `off`,
      'eslint-plugin-import/no-default-export': `off`,
      'eslint-plugin-import/no-nodejs-modules': `off`,
      'eslint-plugin-import/no-unassigned-import': `off`,
      'eslint-plugin-import/no-named-as-default-member': `off`,
      'eslint-plugin-unicorn/filename-case': `off`,
      'oxc/no-rest-spread-properties': `off`,
      'oxc/no-optional-chaining': `off`,
      'oxc/no-async-await': `off`,
      curly: `off`,
      // Too noisy or broad for this app
      'no-magic-numbers': `off`,
      'no-undefined': `off`,
      'no-inline-comments': `off`,
      'no-await-in-loop': `off`,
      'prefer-const': `off`,
      'func-style': `off`,
      'id-length': `off`,
      'sort-imports': `off`,
      'sort-keys': `off`,
      'max-statements': `off`,
      'max-lines-per-function': `off`,
      '@typescript-eslint/explicit-function-return-type': `off`,
      '@typescript-eslint/no-unsafe-type-assertion': `off`,
      '@typescript-eslint/prefer-readonly-parameter-types': `off`,
      'eslint-plugin-vitest/no-conditional-in-test': `off`,
      'eslint-plugin-vitest/prefer-importing-vitest-globals': `off`,
    },
  },
  plugins: [sveltekit(), yaml()],
  preview: {
    port: 3000,
  },

  server: {
    fs: { allow: [`../..`] }, // Needed to import from $root
    port: 3000,
  },
})
