name: Link check

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *' # monthly
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v6

      - name: Discover broken links
        uses: lycheeverse/lychee-action@v2
        with:
          args: >-
            --accept 200..=206,429,403,500,502,503
            --max-retries 3
            --retry-wait-time 5
            --timeout 60
            --exclude '%7B'
            --exclude 'npmjs.com'
            --exclude 'linkedin.com'
            --exclude 'github.com/janosh/awesome-sveltekit/network'
            --exclude 'tauri.app'
            --exclude 'sass-lang.com'
            --exclude 'multimonitorcalculator.com'
            --exclude 'lodash.com'
            --exclude 'learninpublic.org'
            --exclude 'parks.lol'
            -- ./**/*.{md,svelte,ts,yml}
