name: Update readme + site screenshots on changed sites.yml

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 */3 *' # https://crontab.guru/every-quarter

jobs:
  new-site:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'janosh'
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
          cache-dependency-path: site/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm add puppeteer js-yaml imagemin imagemin-webp

      - name: Update existing site screenshots and repo contributors on scheduled runs
        if: github.event_name == 'schedule'
        run: node site/scripts/index.js update-existing

      - name: Add screenshots for new sites and update readme
        if: github.event_name != 'schedule'
        run: node site/scripts/index.js

      - name: Push changes if any
        run: |
          if git diff --quiet site/static/screenshots readme.md; then
            echo "No changes to commit"
            exit 0
          fi
          git config user.name 'Janosh Riebesell'
          git config user.email janosh.riebesell@gmail.com
          git add readme.md site/static/screenshots
          git commit -m 'update readme + screenshots'
          git push
